name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: v
        run: echo "VER=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Verify .toc version matches tag
        run: |
          toc_ver=$(grep -E "^## Version:" MaxDps_PriorityIcon/MaxDps_PriorityIcon.toc | sed -E 's/^## Version:[[:space:]]*//')
          if [ "$toc_ver" != "${{ steps.v.outputs.VER }}" ]; then
            echo "TOC version ($toc_ver) != tag (${{ steps.v.outputs.VER }})"; exit 1
          fi

      - name: Build zip
        run: |
          zip -r -X "MaxDps_PriorityIcon-${{ steps.v.outputs.VER }}.zip" MaxDps_PriorityIcon \
            -x "MaxDps_PriorityIcon/.git/*" "**/.DS_Store"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "MaxDps_PriorityIcon-${{ steps.v.outputs.VER }}.zip"
